[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
remappings = ["forge-std/=lib/forge-std/src/"]
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
local = "http://localhost:8545"

[etherscan]